#ifndef S21_DECIMAL_DECIMAL_LIB_SHIFT_DEFS_H_
#define S21_DECIMAL_DECIMAL_LIB_SHIFT_DEFS_H_

#define UINT64_RIGHT_HALF_MASK 0x00000000FFFFFFFF
#define INT_BITS 32
#define DECIMAL_BITS 96
#define POSITIVE_SIGN 0U
#define NEGATIVE_SIGN 1U

#define MAX_DECIMAL_DIGITS_COUNT 29

#endif  // S21_DECIMAL_DECIMAL_LIB_SHIFT_DEFS_H_
